- name: Remove kickstart user 
  user: name=kickstart state=absent remove=yes

- name: Make sure the kickstart group has been removed
  group: name=kickstart state=absent

- name: Add puppet repo.
  yum: name=http://yum.puppetlabs.com/puppetlabs-release-el-7.noarch.rpm state=present update_cache=yes

- name: Install the latest version of Puppet and ntp.
  yum: name=puppet state=present
  with_items:
    - ntp
    - puppet

- name: Copy the hosts file to ensur all names resolve correctly 
  template: src=hosts dest=/etc/hosts

- name: Cope the new puppet config to puppet agents
  template: src=hosts dest=/etc/hosts

- name: Add puppet to startup
  command: /usr/sbin/chkconfig puppet on

- name: Restart puppet agent
  service: name=puppet state=restarted

- name: Ensure puppet agent has been started
  service: name=puppet state=started